# Generated by Django 4.1.7 on 2023-05-15 07:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=20, null=True, verbose_name='Company Name')),
                ('oname', models.CharField(max_length=20, null=True, verbose_name='Company Owner Name')),
                ('compemail', models.EmailField(max_length=20, null=True, verbose_name='Email')),
                ('compphone', models.CharField(max_length=10, null=True, verbose_name='Phone')),
                ('compaddress', models.TextField(max_length=50, null=True, verbose_name='Address')),
                ('lapm', models.IntegerField(null=True, verbose_name='Leaves allowed per month')),
                ('plgm', models.IntegerField(null=True, verbose_name='Paid Leaves given per month')),
                ('offleave', multiselectfield.db.fields.MultiSelectField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True, verbose_name='Weekend Official Leave')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, null=True, verbose_name='Client')),
                ('prjtitle', models.CharField(max_length=50, null=True, verbose_name='Project Title')),
                ('siteloc', models.TextField(max_length=50, null=True, verbose_name='Site Location')),
                ('startdt', models.DateTimeField(default=datetime.datetime.now, help_text='Please use the following format: <em>YYYY-MM-DD HH:MM:SS</em>.', verbose_name='Starting Date')),
                ('region', models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3')], default='Service Provider', max_length=50, null=True, verbose_name='Region')),
                ('description', models.TextField(max_length=50, null=True, verbose_name='Description')),
                ('prjhead', models.CharField(max_length=100, null=True, verbose_name='Project Head')),
                ('regionhead', models.CharField(max_length=100, null=True, verbose_name='Region Head')),
                ('sitehead', models.CharField(max_length=100, null=True, verbose_name='Site Head')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junior', models.CharField(max_length=255, null=True, verbose_name='Junior')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Mapping',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='Phone')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=20, null=True, verbose_name='Blood Group')),
                ('econtactname', models.CharField(max_length=30, null=True, verbose_name='Emergency Contact Name')),
                ('econtactphone', models.CharField(max_length=10, null=True, verbose_name='Emergency Contact Number')),
                ('empid', models.CharField(max_length=20, null=True, unique=True, verbose_name='Employee ID')),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], default='Employee', max_length=50, verbose_name='Select your role')),
                ('doj', models.DateTimeField(default=datetime.datetime.now, help_text='Please use the following format: <em>YYYY-MM-DD HH:MM:SS</em>.', verbose_name='Date of Joining')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('Production', 'Production'), ('Sales', 'Sales'), ('HR', 'HR'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='IT', max_length=20, null=True, verbose_name='Department')),
                ('designation', models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('Site Head', 'Site Head'), ('Region Head', 'Region Head'), ('Manager', 'Manager'), ('HR', 'HR'), ('Director', 'Director'), ('President', 'President'), ('CEO', 'CEO'), ('Owner', 'Owner'), ('Other', 'Other')], default='Employee', max_length=20, null=True, verbose_name='Designation')),
                ('emptype', models.CharField(choices=[('Permanent Employee', 'Permanent Employee'), ('Contract Based', 'Contract Based')], default='Permanent Employee', max_length=20, null=True, verbose_name='Employment Type')),
                ('salary', models.IntegerField(null=True, verbose_name='Salary')),
                ('per', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month')], default='Month', max_length=20, null=True, verbose_name='Per')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20, null=True, unique=True, verbose_name='Client ID')),
                ('ctype', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='Individual', max_length=20, null=True, verbose_name='Client Type')),
                ('compname', models.CharField(max_length=100, null=True, verbose_name='Company Name')),
                ('compweb', models.CharField(max_length=100, null=True, verbose_name='Company Website')),
                ('typeob', multiselectfield.db.fields.MultiSelectField(choices=[('Service Provider', 'Service Provider'), ('Manufacturer', 'Manufacturer'), ('Consultant', 'Consultant'), ('Traders and Distributors', 'Traders and Distributors'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Type of Business')),
                ('cfirstname', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('clastname', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('cpcm', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], default='Phone', max_length=50, null=True, verbose_name='Preferred Contact Method')),
                ('cemail', models.EmailField(max_length=20, null=True, verbose_name='Email')),
                ('cphone', models.CharField(max_length=10, null=True, verbose_name='Phone')),
                ('caddress', models.TextField(max_length=50, null=True, verbose_name='Address')),
                ('ainfo', models.TextField(max_length=50, null=True, verbose_name='Additional Information')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Today Date')),
                ('attendance', models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='Attendance')),
                ('mapping', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.mapping')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
    ]
