# Generated by Django 4.1.7 on 2023-05-15 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedAtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Today Date')),
                ('attendance', models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='Attendance')),
                ('approved_timestamp', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.mapping')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ApprovedAtt',
            },
        ),
    ]
