# Generated by Django 4.1.7 on 2023-05-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_approvedatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedatt',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
    ]
