# Generated by Django 4.1.7 on 2023-05-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_alter_approvedatt_name_alter_approvedatt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedatt',
            name='name',
        ),
    ]
