# Generated by Django 4.1.7 on 2023-04-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='option',
        ),
    ]
