# Generated by Django 4.1.7 on 2023-05-16 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0006_approvedatt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='jrname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jrname', to=settings.AUTH_USER_MODEL),
        ),
    ]
