# Generated by Django 4.1.7 on 2023-04-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_remove_employee_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='junior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_junior', to='Attendance.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='senior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_senior', to='Attendance.employee'),
        ),
    ]
