# Generated by Django 4.1.7 on 2023-05-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_mapping_jrname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='jrname',
        ),
    ]
