# Generated by Django 4.1.7 on 2023-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0008_remove_mapping_jrname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ainfo',
            field=models.TextField(max_length=100, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='client',
            name='caddress',
            field=models.TextField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cemail',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='compaddress',
            field=models.TextField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='compemail',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='compname',
            field=models.CharField(max_length=50, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='oname',
            field=models.CharField(max_length=50, null=True, verbose_name='Company Owner Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('Production', 'Production'), ('Sales', 'Sales'), ('HR', 'HR'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='IT', max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtactname',
            field=models.CharField(max_length=50, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emptype',
            field=models.CharField(choices=[('Permanent Employee', 'Permanent Employee'), ('Contract Based', 'Contract Based')], default='Permanent Employee', max_length=30, null=True, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=100, null=True, verbose_name='Description'),
        ),
    ]
