# Generated by Django 4.1.7 on 2023-04-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0008_attendance_junior_attendance_senior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='junior',
        ),
    ]
