# Generated by Django 4.1.7 on 2023-05-18 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0009_alter_client_ainfo_alter_client_caddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='compaddress',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'tdate')},
        ),
    ]
