# Generated by Django 4.1.7 on 2023-04-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0009_remove_attendance_junior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='senior',
        ),
    ]
