# Generated by Django 4.1.7 on 2023-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0010_remove_attendance_senior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='junioratt',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], max_length=100, null=True, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='senioratt',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], max_length=100, null=True, verbose_name='My Attendance'),
        ),
    ]
