# Generated by Django 4.1.7 on 2023-05-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0010_alter_company_compaddress_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
