# Generated by Django 4.1.7 on 2023-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0011_alter_attendance_junioratt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='senior',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='junioratt',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='senioratt',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='My Attendance'),
        ),
    ]
