# Generated by Django 4.1.7 on 2023-04-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0013_mapping_senior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='senior',
        ),
    ]
