# Generated by Django 4.1.7 on 2023-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0015_mapping_senior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='senior',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='tdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Today Date'),
        ),
    ]
