# Generated by Django 4.1.7 on 2023-04-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0017_mapping_senior_alter_attendance_tdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='senior',
        ),
    ]
