# Generated by Django 4.1.7 on 2023-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0023_alter_mapping_junior'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sttime',
            field=models.TimeField(null=True),
        ),
    ]
