# Generated by Django 4.1.7 on 2023-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0024_company_endtime_company_sttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='endtime',
            field=models.TimeField(null=True, verbose_name='Ending Time'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sttime',
            field=models.TimeField(null=True, verbose_name='Starting Time'),
        ),
    ]
