# Generated by Django 4.1.7 on 2023-04-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0025_alter_company_endtime_alter_company_sttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sttime',
            field=models.TimeField(null=True),
        ),
    ]
