# Generated by Django 4.1.7 on 2023-04-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0026_alter_company_endtime_alter_company_sttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sttime',
        ),
    ]
