# Generated by Django 4.1.7 on 2023-04-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0027_remove_company_endtime_remove_company_sttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
