# Generated by Django 4.1.7 on 2023-04-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0028_userdata_is_staff_userdata_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_superuser',
        ),
    ]
