# Generated by Django 4.1.7 on 2023-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0029_remove_userdata_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('HR', 'HR'), ('Admin', 'Admin')], max_length=50, verbose_name='Select your role'),
        ),
    ]
