# Generated by Django 4.1.7 on 2023-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0030_alter_userdata_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('Admin', 'Admin')], max_length=50, verbose_name='Select your role'),
        ),
    ]
