# Generated by Django 4.1.7 on 2023-04-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0031_alter_userdata_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
