# Generated by Django 4.1.7 on 2023-04-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0032_remove_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='juniors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.mapping'),
        ),
    ]
