# Generated by Django 4.1.7 on 2023-04-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0033_attendance_juniors'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Admin', 'Admin')], default='Employee', max_length=50, verbose_name='Select your role'),
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
