# Generated by Django 4.1.7 on 2023-04-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0034_employee_role_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], default='Employee', max_length=50, verbose_name='Select your role'),
        ),
    ]
