# Generated by Django 4.1.7 on 2023-04-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0035_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='junioratt',
        ),
    ]
