# Generated by Django 4.1.7 on 2023-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0036_remove_attendance_junioratt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='junioratt',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='Attendance'),
        ),
    ]
