# Generated by Django 4.1.7 on 2023-04-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0037_attendance_junioratt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='junior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee'),
        ),
    ]
