# Generated by Django 4.1.7 on 2023-04-20 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0042_alter_mapping_junior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='junior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junior_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Junior'),
        ),
    ]
