# Generated by Django 4.1.7 on 2023-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0053_alter_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='Attendance'),
        ),
    ]
