# Generated by Django 4.1.7 on 2023-04-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0054_alter_attendance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='juid',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='entryid', to=settings.AUTH_USER_MODEL),
        ),
    ]
