# Generated by Django 4.1.7 on 2023-04-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0056_alter_employee_juid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='juid',
        ),
    ]
