# Generated by Django 4.1.7 on 2023-04-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0058_alter_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='att1',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='Attendance'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='jid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee'),
        ),
    ]
