# Generated by Django 4.1.7 on 2023-04-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0059_remove_attendance_attendance_attendance_att1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='jid',
        ),
    ]
