# Generated by Django 4.1.7 on 2023-04-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0060_remove_mapping_jid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='att1',
            new_name='attendance',
        ),
        migrations.AddField(
            model_name='mapping',
            name='jid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee'),
        ),
    ]
