# Generated by Django 4.1.7 on 2023-04-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0062_alter_mapping_jid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='junior',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Attendance.mapping'),
        ),
    ]
