# Generated by Django 4.1.7 on 2023-04-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0063_attendance_junior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='junior',
        ),
    ]
