# Generated by Django 4.1.7 on 2023-04-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0066_alter_mapping_junior'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='juniors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Attendance.mapping'),
        ),
    ]
