# Generated by Django 4.1.7 on 2023-04-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0067_attendance_juniors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='juniors',
        ),
    ]
