# Generated by Django 4.1.7 on 2023-04-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0070_remove_attendance_juniors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='junior',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Attendance.employee'),
        ),
    ]
