# Generated by Django 4.1.7 on 2023-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0073_attendance_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='names',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
