# Generated by Django 4.1.7 on 2023-04-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0074_alter_attendance_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='names',
        ),
    ]
