# Generated by Django 4.1.7 on 2023-04-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0075_remove_attendance_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='jid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee'),
        ),
    ]
