# Generated by Django 4.1.7 on 2023-04-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0077_alter_mapping_jid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='jid',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.employee'),
        ),
    ]
