# Generated by Django 4.1.7 on 2023-04-25 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0087_alter_mapping_junior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='names',
        ),
        migrations.CreateModel(
            name='JrAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Today Date')),
                ('attendance', models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Overtime', 'Overtime'), ('Absent', 'Absent')], default='Full Day', max_length=100, null=True, verbose_name='Attendance')),
                ('juniors', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Attendance.mapping')),
            ],
            options={
                'db_table': 'JrAttendance',
            },
        ),
    ]
