# Generated by Django 4.1.7 on 2023-04-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0089_jrattendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrattendance',
            name='juniors',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.mapping'),
        ),
    ]
