# Generated by Django 4.1.7 on 2023-04-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0092_alter_mapping_junior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jrattendance',
            old_name='juniors',
            new_name='mapping',
        ),
    ]
