# Generated by Django 4.1.7 on 2023-04-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0093_rename_juniors_jrattendance_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrattendance',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.mapping'),
        ),
    ]
