# Generated by Django 4.1.7 on 2023-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0094_alter_jrattendance_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrattendance',
            name='mapping',
            field=models.CharField(max_length=255, null=True, verbose_name='Juniors'),
        ),
    ]
