# Generated by Django 4.1.7 on 2023-04-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0095_alter_jrattendance_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='jid',
        ),
    ]
