# Generated by Django 4.1.7 on 2023-04-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0096_remove_mapping_jid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JrAttendance',
        ),
    ]
