# Generated by Django 4.1.7 on 2023-04-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0099_alter_attendance_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mapping',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.mapping'),
        ),
    ]
