# Generated by Django 4.1.7 on 2023-04-28 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0101_alter_attendance_tdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tdate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Today Date'),
        ),
    ]
