# Generated by Django 4.1.7 on 2023-04-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0102_alter_attendance_tdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='empid',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='firstname',
            field=models.CharField(max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='lastname',
            field=models.CharField(max_length=30, null=True, verbose_name='Last Name'),
        ),
    ]
