# Generated by Django 4.1.7 on 2023-04-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0103_mapping_empid_mapping_firstname_mapping_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='lastname',
        ),
    ]
